---
- name: Installing packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ software_packages }}"

- name: Create disk path
  file:
    path: /mnt/ssd2t
    owner: "{{ ansible_user }}"
    recurse: yes

- name: Create a ext4 filesystem on /dev/{{ disk_mount_ssd2t }}
  filesystem:
    fstype: ext4
    dev: "/dev/{{ disk_mount_ssd2t }}"

- name: Mount
  mount:
    path: /mnt/ssd2t
    #src: "/dev/{{ disk_mount_ssd2t }}"
    src: UUID=bdbccbb9-133d-408e-9ff8-55b150e02ca9
    fstype: ext4
    state: mounted

- name: Including line on exports
  lineinfile:
    path: /etc/exports
    regexp: '^/mnt/ssd2t *(rw,no_root_squash,insecure,async,no_subtree_check,anonuid=1000,anongid=1000)'
    line: '/mnt/ssd2t *(rw,no_root_squash,insecure,async,no_subtree_check,anonuid=1000,anongid=1000)'
    insertafter: EOF
  notify: restart_nfs

- name: Create disk path
  file:
    path: /mnt/ssd2t
    owner: "{{ ansible_user }}"
    recurse: yes
