---
- name: "update hostnames"
  hostname:
    name: "{{ new_hostname }}"
  notify: reboot

- name: Include ssd
  include_tasks: ssd.yml

- name: Include ssdchino
  include_tasks: ssdchino.yml

- name: Include seagate
  include_tasks: seagate.yml
