---
k3s_version: v1.22.2+k3s2
ansible_user: pi
#ansible_user: xussof
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
